subscription_id = "a66db4d1-4b92-4c2d-830b-341a8c0b5482"
resource_group_name = "Deployment-Testing-RG"
location = "Central India"
app_service_name = "deployment-testing-app"
app_service_plan_name = "testing-app-plan"
runtime_stack = "NODE"
runtime_version = "18-lts"
always_on = false
use_existing_plan = true